#5. Programa que pida cinco palabras y muestre una frase con las cinco. Modifica el código para que entre palabra y palabra haya una coma.
var1=input("Introduce una primera palabra: ")
var2=input("Introduce una segunda palabra: ")
var3=input("Introduce una tercera palabra: ")
var4=input("Introduce una cuarta palabra: ")
var5=input("Introduce una última palabra: ")
print(var1)
print(var2)
print(var3)
print(var4)
print(var5)
print(var1,",",var2,",",var3,",",var4,",",var5)