#6. A partir del programa 5. Haz que se muestre por pantalla también la frase en el orden inverso en que se han introducido las palabras. 
var1=input("Introduce una primera palabra: ")
var2=input("Introduce una segunda palabra: ")
var3=input("Introduce una tercera palabra: ")
var4=input("Introduce una cuarta palabra: ")
var5=input("Introduce una última palabra: ")
print(var1)
print(var2)
print(var3)
print(var4)
print(var5)
print(var1,var2,var3,var4,var5)
print(var5,var4,var3,var2,var1)