#7. programa que calcule dos operandos con los 7 operadores vistos en clase. ¿Cómo puedes forzar que el resultado de la división tenga 2 decimales?
var1=float(input("Introduce un número: "))
var2=float(input("Introduce otro número: "))
print(var1)
print(var2)
total_suma=round(var1+var2, 2)
print("La suma del primer número y el segundo es:", total_suma)
total_resta=round(var1-var2, 2)
print("La resta del primer número y el segundo es:", total_resta)
total_multiplicación=round(var1*var2, 2)
print("La multiplicación del primer número y el segundo es:", total_multiplicación)
total_división=round(var1/var2, 2)
print("La división del primer número y el segundo es:", total_división)
total_exponenciación=round(var1**var2, 2)
print("La exponenciación del primer número y el segundo es:", total_exponenciación)
total_división_entera=round(var1//var2, 2)
print("La división entera del primer número y el segundo es:", total_división_entera)